<?php

return [
    'home'          => 'fa fa-home',
    'user'          => 'fa fa-user',
    'cog'           => 'fa fa-cog',
    'envelope'      => 'fa fa-envelope',
    'bell'          => 'fa fa-bell',
    'camera'        => 'fa fa-camera',
    'heart'         => 'fa fa-heart',
    'search'        => 'fa fa-search',
    'trash'         => 'fa fa-trash',
    'edit'          => 'fa fa-edit',
    'download'      => 'fa fa-download',
    'upload'        => 'fa fa-upload',
    'lock'          => 'fa fa-lock',
    'unlock'        => 'fa fa-unlock',
    'shopping_cart' => 'fa fa-shopping-cart',
    'calendar'      => 'fa fa-calendar',
    'comments'      => 'fa fa-comments',
    'folder'        => 'fa fa-folder',
    'chart'         => 'fa fa-chart-line',
    'file'          => 'fa fa-file',
    'book'          => 'fa fa-book',
    'key'           => 'fa fa-key',
    'money'         => 'fa fa-money-bill-wave',
    'thumbs_up'     => 'fa fa-thumbs-up',
    'flag'          => 'fa fa-flag',
    'music'         => 'fa fa-music',
    'phone'         => 'fa fa-phone',
    'globe'         => 'fa fa-globe',
    'wifi'          => 'fa fa-wifi',
    'car'           => 'fa fa-car',
    'clock'         => 'fa fa-clock',
    'map'           => 'fa fa-map',
    'star'          => 'fa fa-star',
];
